#!.venv/bin/python

from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter, Namespace, _SubParsersAction
from commands.arguments import SetCommandArguments

from commands.executor_provider import ExecutorProvider


def register_set_command(main_parser: _SubParsersAction) -> ArgumentParser:
    parser: ArgumentParser = main_parser.add_parser('set', help='Change the wallpaper')

    return parser


def register_save_command(main_parser: _SubParsersAction) -> ArgumentParser:
    parser: ArgumentParser = main_parser.add_parser('save', help='Save the current wallpaper')

    return parser


def parse_args() -> Namespace:
    parser = ArgumentParser(formatter_class=ArgumentDefaultsHelpFormatter)
    command_parsers = parser.add_subparsers(dest='command')

    register_set_command(command_parsers)
    register_save_command(command_parsers)

    return parser.parse_args()


def run_command(args: Namespace) -> None:
    executor = ExecutorProvider().provide()

    if args.command == 'set':
        executor.set(SetCommandArguments())

    if args.command == 'save':
        executor.save_current()


def main():
    args = parse_args()
    run_command(args)


if __name__ == '__main__':
    main()
